### ISSUE TITLE
Find responsive solution for inputbox

### ISSUE THREAD

**Issue by davidagustin** [ShelterTechSF/sheltertech.org#106]
I still feel like there's probably a cleaner way to deal with this, but we probably don't need to handle this now. Let's revisit how this input text boxes are handled in the future.

_Originally posted by @richardxia in https://github.com/ShelterTechSF/sheltertech.org/pull/89#discussion_r525873961_

**Comment by richardxia** [comment]
For this, let's do some research on how other React libraries that have form elements handle the styling, to see if there's anything we can learn from how they set it up.

One specific thing that I'd like to have fixed about our InputText element is with how the Footer component's InputText wrapper element behaves. Currently, the way we handle this is asymmetric between desktop resolutions and mobile resolutions. See https://github.com/ShelterTechSF/sheltertech.org/blob/4fef794442e27e55770c5f2fb871f52925abf399/src/components/grid-aware/Footer/SubscriptionBlock/SubscriptionBlock.module.css#L32-L34 and https://github.com/ShelterTechSF/sheltertech.org/blob/4fef794442e27e55770c5f2fb871f52925abf399/src/components/grid-aware/Footer/SubscriptionBlock/SubscriptionBlock.module.css#L68-L71.

If we could be consistent and just pick one style for configuring the properties, rather than just relying on `width` for the desktop viewport and `min-width` on the mobile viewport.

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
