### ISSUE TITLE
VideoSpotlightBlock modal doesn't open in Firefox

### ISSUE THREAD

**Issue by jessica-px** [ShelterTechSF/sheltertech.org#223]
The modal toggled by the `<VideoSpotlightBlock>` component doesn't seem to open in Firefox. You can reproduce this by going to the live site in Firefox and trying to click the play button on this video:

<img width="1305" alt="Screen Shot 2021-04-04 at 6 30 49 PM" src="https://user-images.githubusercontent.com/17056719/113527913-e4f57000-9573-11eb-8a0f-bad967ed8f07.png">

In Chrome, it will open a modal with an embedded YouTube video, which is the expected behavior. In Firefox, nothing happens. Potentially the issue might lie in the CSS somewhere, but I didn't investigate that closely.

**Comment by ivanleeswe** [comment]
Hello @jessica-px and. @richardxia,

So I just looked into this problem and it seems that the div with the class below for bleedMainContent is overlapping bleedImageWrapper causing the click button to be unclickable.

`class="VideoSpotlightBlock-module--bleedMainContent--3ZVF6"`

Would using z-index CSS property work in positioning the bleedMainContent div element under bleedImageWrapper div element?

**Comment by richardxia** [comment]
Interesting, do you know how it behaves on Chrome or Safari? And do you know whether the Firefox behavior is correct, whether the Chrome/Safari behavior is correct, or whether both are valid behaviors? Before just setting a `z-index` property, I'd like to make sure that we understand why we are seeing the behavior we are seeing.

`z-index` is one property that is a bit more "dangerous" to use than other CSS properties since it has a global effect rather than a local one, and it's easy to run into issues with z-index conflicts across different components when you're not careful about it.

If you haven't learned about it there's a very good series of articles on MDN about z-index and the stacking context: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index. The [subarticle on stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) is a particularly useful reference, though you may need to read the earlier articles in order to understand it.

It's pretty important to understand stacking contexts when using z-index, since the only way to localize the impact of a z-index is to effectively use a stacking context to bound its effect.
