### ISSUE TITLE
Update StatsBlock component

### ISSUE THREAD

**Issue by candywang** [ShelterTechSF/sheltertech.org#324]
The large stat number in the StatsBlock component has a font of merriweather, 72px, and 300. We can create a `--font-stat` typography in `global.css` or change the font styling in `StatsBlock.module.css`. @richardxia , which is preferred?

In StatCard, the `secondaryNumber` prop type should be a string or a number.

**Comment by richardxia** [comment]
Nice catch! I think we had hit something similar when we first built out this component for the Volunteer page, where at the time the Figma design had a totally different font than anything else on the site. It looks like after we created the new Impact page designs, we also updated the Volunteer page as well to use Merriweather at 300 weight, so you're right that we should update the styles to match.

Since this style only appears in one component, I think it's fine to continue to define the style within the component's CSS, but I wouldn't be opposed to defining it in global.css if you wanted to.
