### ISSUE TITLE
Improve Images Accessibility

### ISSUE THREAD

**Issue by schroerbrian** [ShelterTechSF/sheltertech.org#353]
See [accessibility spreadsheet](https://docs.google.com/spreadsheets/d/1wk4l1ZjWCvxJF0Xjuco8b-lWVws-Vo0aIIRkCYRjbIc/edit#gid=0) for details

**Comment by zen-gineer** [comment]
Row 26 of the [accessibility spreadsheet](https://docs.google.com/spreadsheets/d/1wk4l1ZjWCvxJF0Xjuco8b-lWVws-Vo0aIIRkCYRjbIc/edit#gid=0) calls for changes to all decorative images so that Assistive Technology ignores reading unnecessary content. I'm not confident that I can discern which images are decorative without further guidance.

**Comment by richardxia** [comment]
Oh, we're no longer updating this codebase anymore, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own. Let me close all tickets in this repository.
