### ISSUE TITLE
Case insensitive File Reader for CircleCI

### ISSUE THREAD

**Issue by davidagustin** [ShelterTechSF/sheltertech.org#78]
![Screen Shot 2020-10-21 at 5 07 43 AM](https://user-images.githubusercontent.com/30575095/96717581-889eeb00-135b-11eb-8fc3-2ecf726b9c4d.png)

There was a situation in the CI where the file name was a different case than the import and caused the CI to fail. Locally this is not an issue for MacOS as the file reader of the operating system is case insensitive. The file reader is case sensitive in the CI although. Is there any way that CircleCI can be configured to resolve paths the same way? @richardxia

**Comment by richardxia** [comment]
This is tied to the file system, and therefore operating system. In general, Linux file systems are case sensitive, and macOS and Windows' file systems are case insensitive, although you are some times able to configure the file systems to switch sensitivity.

I would view this as a bug in our code, since we should make the casing of our code match the casing of the actual files; otherwise, you are going to cause trouble to anyone trying to develop this project on a Linux system, or even anyone running a case sensitive file system on macOS/Windows. As programmers, we already care about case sensitivity in our code (`<Button>` and `<button>` are very different), so why not care about case sensitivity in our file names?

Unrelated, but we don't use CircleCI; we use GitHub Actions in this repo.

**Comment by davidagustin** [comment]
Can a certain linter be configured to check the casing or prettier to auto format the import? And yes, I meant github actions. I would agree that we should care about the casing but this problem is open to happening again.

**Comment by richardxia** [comment]
I'm assuming you are asking whether a linter running on macOS can be configured to check the casing, since on Linux it would just fail?

I don't think this is very easily done and/or might not be possible because you need every tool in the stack to be very careful about how it handles the casing of files on case-insensitive, yet case-preserving file systems. To put it more simply, macOS tries to hide the casing of the files, so you have to do extra work to check for the casing of files.

Of course, if the tools already easily support this, then I'd be in favor of enabling it, so you're free to do some research here if you want.

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
